# Definimos um nome
name: CI/CD - NodeJs

# Quando será executado
# https://docs.github.com/pt/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows
on:
  # Quando houver push na branch "main"
  push:
    branches: [main]
  pull_request:
    # Quando houver PR na branch "main"
    branches: [main]

# Trabalhos que serão executados
jobs:
  # Define o nome (CI, CD, build...)
  ci:
    # Em qual ambiente será executado
    runs-on: ubuntu-latest

    # Se vai rodar em apenas uma versão
    steps:
    - name: Checkout Código
      uses: actions/checkout@v4

    - name: Usando NodeJs 18.x
      uses: actions/setup-node@v4
      with:
        # Definimos a versão que será usada
        node-version: '18.x'
        cache: 'npm'

    - name: Instalar dependencias
      run: npm ci

    - name: Rodando Lint
      run: npm ci:lint

    - name: Rodando Typecheck
      run: npm ci:typecheck

    - name: Rodando Testes
      run: npm ci:test

    # Se precisar rodar em mais de uma versão para
    #strategy:
      #matrix:
        #node-version: [18.x, 20.x, 22.x]

    #steps:
    #- uses: actions/checkout@v4
    #- name: Use Node.js ${{ matrix.node-version }}
    #  uses: actions/setup-node@v4
    #  with:
    #    node-version: ${{ matrix.node-version }}
    #    cache: 'npm'
